config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :policies, only: %i[new create]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'policies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :omniauthable, omniauth_providers: %i[google_oauth2 cognito_idp]

  def self.from_omniauth(auth)
    find_or_create_by!(email: auth.info.email, provider: auth.provider) do |user|
      user.uid = auth.uid
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  def index
    @policies = JSON.parse(build_request(query_policies).body)['data']['policies']
  end

  def new; end

  def create
    build_request(mutation_policy)
    flash[:success] = 'Policy created'
    redirect_to root_path
  end

  private

  def build_request(graphql_query)
    url = URI.parse('http://rails-graphql:9999/graphql')
    http = Net::HTTP.new(url.host, url.port)

    request = Net::HTTP::Post.new(url.request_uri, build_headers)
    request.body = { query: graphql_query }.to_json

    http.request(request)
  end

  def build_headers
    {
      'Authorization' => "Bearer #{encoded_token}",
      'Content-Type' => 'application/json'
    }
  end

  def encoded_token = JWT.encode({}, ENV['SECRET_KEY'], 'HS256')

  def mutation_policy
    <<-GRAPHQL
      mutation {
        createPolicy(
          emissionDate: #{params[:emission_date]},
          endDateCoverage: #{params[:end_date_coverage]},
          vehicle: {
            brand: #{params[:vehicle_brand]},
            licensePlate: #{params[:vehicle_lisence_plate]},
            model: #{params[:vehicle_model]},
            year: #{params[:vehicle_year]}
          },
          insured: {
            name: #{params[:insured_name]},
            cpf: #{params[:insured_cpf]}
          }
        )
      }
    GRAPHQL
  end

  def query_policies
    <<-GRAPHQL
      query {
        policies {
          policyId
          emissionDate
          endDateCoverage
          vehicle {
            brand
            model
            year
          }
          insured {
            name
            cpf
          }
        }
      }
    GRAPHQL
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def omniauth
    @user = User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |user|
      user.email = auth['info']['email']
    end

    redirect_to root_path if @user.valid?
  end

  private

  def auth
    @auth = request.env['omniauth.auth']
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :verify_authenticity_token, only: %i[google_oauth2 cognito_idp]

    def google_oauth2
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        redirect_to root_path
        set_flash_message(:notice, :success, kind: 'Google')
      else
        redirect_to new_user_session_url
        set_flash_message(:notice, :failure, kind: 'Google', reason: 'login')
      end
    end

    def cognito_idp
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        redirect_to root_path
        set_flash_message(:notice, :success, kind: 'Cognito')
      else
        redirect_to new_user_session_url
        set_flash_message(:notice, :failure, kind: 'Cognito', reason: 'login')
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <% if flash[:success] %>
      <div>
        <%= flash[:success] %>
      </div>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/policies/index.html.erb
<h1>Lista de polices</h1>

<ul>
  <% @policies.each do |police| %>
    <li><%= police['policyId'] %></li>
  <% end %>
</ul>

app/views/policies/new.html.erb
<%= form_with url: policies_path, method: :post do |form|%>
  <div>
    <h2>Insured</h2>
    <div>
      <%= form.label :insured_cpf, 'CPF' %>
      <%= form.text_field :insured_cpf %>
    </div>

    <div>
      <%= form.label :insured_name, 'Name' %>
      <%= form.text_field :insured_name %>
    </div>
  </div>

  <div>
    <h2>Policy</h2>
    <div>
      <%= form.label :emission_date, 'Emission date' %>
      <%= form.date_field :emission_date %>
    </div>

    <div>
      <%= form.label :end_date_coverage, 'End date coverage' %>
      <%= form.date_field :end_date_coverage %>
    </div>
  </div>

  <div>
    <h2>Vehicle</h2>
    <div>
      <%= form.label :vehicle_brand, 'Brand' %>
      <%= form.text_field :vehicle_brand %>
    </div>

    <div>
      <%= form.label :vehicle_model, 'Model' %>
      <%= form.text_field :vehicle_model %>
    </div>

    <div>
      <%= form.label :vehicle_year, 'Year' %>
      <%= form.text_field :vehicle_year %>
    </div>

    <div>
      <%= form.label :vehicle_licence_plate, 'License plate' %>
      <%= form.text_field :vehicle_licence_plate %>
    </div>
  </div>

  <%= form.submit 'Create' %>
<% end %>